---
output: github_document
bibliography: references.bib
---


<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# FuzzyImputationTest

<!-- badges: start -->
<!-- badges: end -->

The goal of FuzzyImputationTest is to impute (i.e., replace missing values given by NAs) dataset that
consists of triangular or trapezoidal fuzzy numbers, and check quality of such an imputation.
To impute fuzzy values, various imputation methods - both general (like miceRanger, missingForest, knn),
and specific ones (d-imputation method, abbreviated as DIMP, see [@rb23]) - can be used.
To check the quality of the imputation process, the dataset without missing values can be specified, and then
it is tested with the whole set of procedures.
These procedures are related to calculation of various sample statistics like the mean, standard deviation, and some special distance 
measures for fuzzy numbers, together with obtaining different error values, and conduction of statistical
tests based on the epistemic bootstrap (see [@grzegorzewski2021;@Grzegorzewski_Romaniuk_2022;@PGMR2024AMS]) from 
\code{FuzzySimRes} package (see [@FuzzySimResart]).
There are also special procedures to fuzzify the input and introduce some NAs when necessary.

The following procedures are available in the library:

+ Imputation procedures:
  + *FuzzyImputation* - The main method to impute fuzzy values.
  + *ImputationDimp* - The DIMP (d-imputation) method for fuzzy numbers.
  
+ Testing procedures:
  + *ImputationTests* - The main benchmark function to check the quality of the imputed fuzzy values.
  + *MethodsComparison* - The benchmark function for the built-in imputation methods with many repetitions.
  + *ErrorMatrix* - Calculation of the various errors between two datasets - the true and the imputed one.
  + *StatisticalMeasures* - Calculation of the various statistical measures between the real and imputed data.
  + *ApplyStatisticalTests* - Statistical epistemic tests the imputed values.
  
+ Conversion procedures:
  + *FuzzyNumbersToMatrix* - Conversion of a list of fuzzy numbers into a matrix.
  + *MatrixToFuzzyNumbers* - Conversion of a matrix to a list of fuzzy numbers.
  
+ Calculation of the distance measures:
  + *MeasureAHD* - Calculation of the AHD (Area Hight Distance) measure between two trapezoidal or triangular fuzzy numbers.
  + *MeasureHSD* - Calculation of the HSD (Hight Source Distance) measure between two trapezoidal or triangular fuzzy numbers.
  + *MeasureEuclidean* - Calculation of the Euclidean measure between two trapezoidal or triangular fuzzy numbers.
  
+ Additional procedures:
  + *IntroducingNA* - Introducing NAs to the specified matrix.
  + *RemoveNotFuzzy* - Removing values that are not fuzzy numbers.
  + *FuzzifyMatrix* - Fuzzify the real-valued variables and construct trapezoidal or triangular fuzzy numbers.



## Installation

You can install the development version of FuzzyImputationTest from [GitHub](https://github.com/) with:

``` r
library(devtools)
install_github("mroman-ibs/FuzzyImputationTest")
```




## Example






## References

